---
title: "Getting started with SGPmatrices"
author: "Damian W Betebenner"
date: "`r toOrdinal::toOrdinalDate()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Getting started with SGPmatrices}
  %\VignetteEngine{knitr::rmarkdown}
  %\usepackage[utf8]{inputenc}
---

```{r include = FALSE}
library(SGPmatrices)
is_html_output = function() {
  knitr::opts_knit$get("rmarkdown.pandoc.to")=="html"
}
knitr::opts_chunk$set(
    collapse = TRUE,
    comment = "",
    prompt=TRUE,
    fig.dpi = 96
			)
if (is_html_output()) {
    options(width=1000)
}
```

# Introduction

The R package **SGPmatrices** contains baseline coefficient matrices for use with the SGP in calculating baseline SGPs.
The package is under active development by staff at the [Center for Assessment](https://www.nciea.org).

# Contents

The baseline coefficient matrices embedded in **SGPmatrices** are updated periodically. Current contents include:

* AZ_Baseline_Matrices: Contains 2021 baseline matrices for Arizona AzM2.
* CO_Baseline_Matrices: Contains 2021 baseline matrices for Colorado CMAS.
* HI_Baseline_Matrices: Contains 2021 baseline matrices for Hawaii SBA.
* IN_Baseline_Matrices: Contains 2021 baseline matrices for Indiana ILEARN/ISTEP+.
* MA_Baseline_Matrices: Contains 2021 baseline matrices for Massachusetts MCAS 2.0/PARCC.
* RI_Baseline_Matrices: Contains 2021 baseline matrices for Rhode Island RICAS/PARCC.
* WIDA_Baseline_Matrices: Contains 2021 baseline matrices for multiple WIDA members.
* WIDA_CO_Baseline_Matrices: Contains 2021 baseline matrices for Colorado WIDA-ACCESS.
* WIDA_HI_Baseline_Matrices: Contains 2021 baseline matrices for Hawaii WIDA-ACCESS.
* WIDA_IN_Baseline_Matrices: Contains 2021 baseline matrices for Indiana WIDA-ACCESS.
* WIDA_MA_Baseline_Matrices: Contains 2021 baseline matrices for Massachusetts WIDA-ACCESS.
* WIDA_NH_Baseline_Matrices: Contains 2021 baseline matrices for New Hampshire WIDA-ACCESS.
* WIDA_RI_Baseline_Matrices: Contains 2021 baseline matrices for Rhode Island WIDA-ACCESS.

# Use of SGPmatrices

After [installing](../index.html#installation) the package from GitHub, one conducts baseline SGP calculations with the matrices in this package.
Baseline matrices are added to the `SGPstateData` object embedded in the `SGP` prior to running `SGP` analyses supply the appropriate state abbreviation and year
to the `addBaselineMatrices` function. For example:

```
SGPstateData <- SGPmatrices::addBaselineMatrices("AZ", "2021")
```

# Examples

```
SGPstateData <- SGPmatrices::addBaselineMatrices("WIDA", "2021", add.matrices.to.which.state="WIDA_RI")
```

# Contributions & Requests

If you have contributions of baseline matrices or a feature request for the **SGPmatrices** package, don't hesitate to write or set
up an [issue on GitHub](https://github.com/CenterForAssessment/SGPmatrices/issues).
